### ISSUE TITLE
Not boot at startup

### ISSUE THREAD

**Issue by Ares-87** [TOLDOTECHNIK/Raspberry-Pi-Kiosk-Display-System#1]
Hello,
thank you for your project, I tried it on my Raspberry Pi 4 4gb, Raspberry Pi OS 64bit (released 2024-07-04), but after starting your script successfully, nothing happened on next reboot. No errors during the installation. It starts the desktop normally.

How I can solve this?

Thank you.

**Comment by TOLDOTECHNIK** [comment]
Did you install the Raspberry Pi OS **Lite**?

**Comment by Ares-87** [comment]
Yes, Raspberry Pi OS Lite

**Comment by edmilton-sg** [comment]
Hello, I would like to start by thanking you for the script, it really helped a lot.

I'm having a hard time setting the screen to 90° rotation, I've tried several ways, but nothing seems to rotate the screen.

nano /home/$USER/.config/labwc/autostart

wlr-randr --output card1-HDMI-A-1 --transform 90

but without success.

what would be the correct way to do this, thank you very much!

**Comment by TOLDOTECHNIK** [comment]
Try using
`wlr-randr --output HDMI-A-1 --transform 90` in your `autostart` file. You can also test the rotation in the terminal first before adding it to the autostart file.

Ensure you're connected to the right display port (e.g. HDMI-A-1). Do this by just running `wlr-randr` in your terminal.

**Comment by Ares-87** [comment]
> We've completely rewritten the setup script. It now supports almost all Raspberry Pi boards. Could you please test the installation again? Simply run: `bash <(curl -s https://raw.githubusercontent.com/TOLDOTECHNIK/Raspberry-Pi-Kiosk-Display-System/main/kiosk_setup.sh)`

Nice, this works also into Raspberry Zero 2W 512mb, but chromium in this case is tooo slow.
Works on Raspberry Pi 4 4gb

Anyway, I have the same problem about the screen rotation. With `wlr-randr --output HDMI-A-1 --transform 90 not works` other suggestions?

**Comment by TOLDOTECHNIK** [comment]
Which system did you test this on?

**Comment by Ares-87** [comment]
Raspberry Pi Os Lite 64bit with no desktop environment

**Comment by TOLDOTECHNIK** [comment]
Hardware?

**Comment by Ares-87** [comment]
Any news? Unfortunately tomorrow I have a fair with 8 totems vertically  😓 I tried also in cmdline.txt but nothing, I'm missing some thing.

**Comment by Ares-87** [comment]
I solved the problem, wlr-randr it wasn't installed, probably because the `labwc` installation was limited by essential elements, because you using the `--no-install-recommends` command. I installed wlr-randr separately with `sudo apt install wlr-randr` after the reboot it worked. You could include this line in your .sh file, and maybe add also an option to set the screen rotation and the touch coordinates.

**Comment by Ares-87** [comment]
> 
I solved the problem, wlr-randr it wasn't installed, probably because the `labwc` installation was limited by essential elements, because you using the `--no-install-recommends` command. I installed wlr-randr separately with `sudo apt install wlr-randr` after the reboot it worked. You could include this line in your .sh file, and maybe add also an option to set the screen rotation and the touch coordinates. A this time the touchscreen still needs to be calibrated, but I can't seem to get it right, please can you help me?

**Comment by TOLDOTECHNIK** [comment]
We have just added the installation of `wlr-randr`. Rotation will not be implemented. Closing for now.
